apiVersion: v1
kind: Service
metadata:
  name: penny-k8s-backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: penny-k8s-backend  # This should match the backend's app label
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: penny-k8s-frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: penny-k8s-frontend
  ports:
    - port: 80
      targetPort: 80   # Correct targetPort for frontend
