apiVersion: v1
kind: ServiceAccount
metadata:
  name: penny-k8s-sa
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: penny-k8s-role
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "nodes", "configmaps"]
    verbs: ["get", "list", "watch"]
---
{{- if .Values.installClusterRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: penny-k8s-rolebinding
  namespace: penny-k8s
subjects:
  - kind: ServiceAccount
    name: penny-k8s-sa
    namespace: penny-k8s
roleRef:
  kind: ClusterRole
  name: penny-k8s-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}