apiVersion: v1
kind: ServiceAccount
metadata:
  name: penny-k8s-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: penny-k8s-role
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: penny-k8s-rolebinding
subjects:
  - kind: ServiceAccount
    name: penny-k8s-sa
    namespace: default # Change this if your app is in a different namespace
roleRef:
  kind: ClusterRole
  name: penny-k8s-role
  apiGroup: rbac.authorization.k8s.io