name: Build and Push Docker Images to GHCR

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-backend:
    name: Build and Push Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build and Test Spring Boot Application
        working-directory: penny-k8s-backend
        run: mvn clean verify

      - name: Package Spring Boot Application
        working-directory: penny-k8s-backend
        run: mvn package -DskipTests

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image for Backend
        run: |
          docker build -f penny-k8s/penny-k8s-backend/Dockerfile \
            -t ghcr.io/${{ github.repository_owner }}/penny-k8s-backend:${{ github.sha }} \
            penny-k8s/penny-k8s-backend

      - name: Push Docker Image for Backend
        run: docker push ghcr.io/${{ github.repository_owner }}/penny-k8s-backend:${{ github.sha }}

  build-frontend:
    name: Build and Push Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies and Build Frontend
        working-directory: penny-k8s-frontend
        run: |
          npm install
          npm run build

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image for Frontend
        run: |
          docker build -f penny-k8s/penny-k8s-frontend/Dockerfile \
            -t ghcr.io/${{ github.repository_owner }}/penny-k8s-frontend:${{ github.sha }} \
            penny-k8s/penny-k8s-frontend

      - name: Push Docker Image for Frontend
        run: docker push ghcr.io/${{ github.repository_owner }}/penny-k8s-frontend:${{ github.sha }}
