name: Build and Push Docker Images to GHCR

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-backend:
    name: Build and Push Backend
    runs-on: ubuntu-latest
    steps:
      - name: Set lowercase repo owner
        id: repo
        run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

#      - name: Build and Test Spring Boot Application
#        working-directory: penny-k8s-backend
#        run: mvn clean verify

      - name: Package Spring Boot Application
        working-directory: penny-k8s-backend
        run: mvn package -DskipTests

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image for Backend
        working-directory: penny-k8s-backend
        run: |
          docker build -f Dockerfile \
            -t ghcr.io/${{ env.REPO_OWNER_LC }}/penny-k8s-backend:${{ github.sha }} .

      - name: Push Docker Image for Backend
        run: docker push ghcr.io/${{ env.REPO_OWNER_LC }}/penny-k8s-backend:${{ github.sha }}

  build-frontend:
    name: Build and Push Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Set lowercase repo owner
        id: repo
        run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies and Build Frontend
        working-directory: penny-k8s-frontend
        run: |
          npm install
          npm run build

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image for Frontend
        working-directory: penny-k8s-frontend
        run: |
          docker build -f Dockerfile \
            -t ghcr.io/${{ env.REPO_OWNER_LC }}/penny-k8s-frontend:${{ github.sha }} .

      - name: Push Docker Image for Frontend
        run: docker push ghcr.io/${{ env.REPO_OWNER_LC }}/penny-k8s-frontend:${{ github.sha }}
